### ISSUE TITLE
Autoload Klassen

### ISSUE THREAD

**Issue by wende60** [FriendsOfREDAXO/theme#2]
hi,

wenn ich das richtig verstanden habe, kann man im Ordner theme/privat/lib/ z.B MyHelper.php mit der Klasse MyHelper ablegen und dann problemlos überall mit MyHelper::myStaticMethod() nutzen. Falls dem so ist wäre es imho cool, so eine kleine Beschreibung in die readme mit aufzunehmen, denn wer mit solchen Autoload Mechanismen nicht so vertraut ist muss sonst ganz schön frickeln ;)

Sehr praktisch ansonsten :)

Grüsse, Jo

**Comment by DanielWeitenauer** [comment]
Wie meinst du das? Soll die vorhandene Beschreibung der Ordner ausführlicher sein, oder ist sie missverständlich? 
Das Verhalten selbst entspricht dem der normalen Redaxo-Addon-Ordner. 
Wäre es evtl. sinnvoller, eine grundsätzliche Beschreibung der Addon-Ordner zu schreiben, auf die ich dann verweisen könnte?

**Comment by wende60** [comment]
hm, mein php ist etwas eingerostet, ich bin mit diesen Autoload Mechanismen nicht sehr vertraut. Für mich wäre eine etwas ausführlichere Beschreibung nützlich gewesen. Im ersten Versuch habe ich eine Klasse MyClass in der functions.php notiert - das gab einen Fehler. Inzwischen habe ich auch gelernt, dass dieses Verhalten eines Addon-Ordners in Redaxo üblich ist ;)

**Comment by DanielWeitenauer** [comment]
Wie lautete der Fehler? War es ein 'class already exists'? 
Die functions.php wird vom Autoloader indexiert. Ich glaube, wenn die Klasse angesprochen wird, bevor die functions.php inkludiert wurde, könnte es zur doppelten Deklaration und einem Fehler kommen. Das müsste behoben werden, damit das ganze intuitiver wird.

**Comment by wende60** [comment]
jep der wars...

**Comment by DanielWeitenauer** [comment]
fixed by #3
