### ISSUE TITLE
Templates und Modulen tatsächlichen Namen geben

### ISSUE THREAD

**Issue by Pixeldaniel** [FriendsOfREDAXO/theme#20]
Wäre super, wenn die Dateien nicht nur template.php bzw. modul.php heißen, sondern so wie der Ordner in dem sie liegen (Name des Templates/Moduls im Backend).
Im Editor hat man sonst bspw. 3 mal template.php offen und verliert leicht den Überblick.

**Comment by DanielWeitenauer** [comment]
Diese Einstellung findest du im Developer-Addon. Die Option heiß "Präfix für Dateinamen (enthält ID und Name)".
