### ISSUE TITLE
Sync von : YForm: E-Mail-Templates

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/theme#21]
Anpassung an das aktuelle Developer AddOn

**Comment by novinet-dsteffen** [comment]
@olien https://github.com/FriendsOfREDAXO/theme/pull/22

**Comment by anveno** [comment]
@DanielWeitenauer Sorry. Lese gerade auf Slack, dass ich dich hätte vorher fragen sollen. Habe schon gemerged. War das okay?
