### ISSUE TITLE
redaxo 5.12.0-beta2 Warning

### ISSUE THREAD

**Issue by rotzek** [FriendsOfREDAXO/theme#27]
Es erscheint im Frontend die Warnung:

Warning: rex_extension::register: Argument $level should be one of the constants rex_extension::EARLY/NORMAL/LATE, but string "LATE" given in redaxo/src/core/lib/extension.php on line 87

**Comment by DanielWeitenauer** [comment]
Das ist ein Fehler, den du manuell beheben musst, da es sich bei dem lediglich um ein Beispiel handelt und die Datei functions.php nach dem ersten Anlegen vom Addon nicht mehr verändert wird.
Wenn du diesen Code-Teil nicht nutzt, kannst du ihn auch einfach löschen.

Für zukünftige Projekte ist der Code in der nächsten Version angepasst und vollständig auskommentiert, um den Beispielcharakter zu unterstreichen: 9f8dcebf329319779effe2144b8c6c504df8770e

**Comment by DanielWeitenauer** [comment]
Um Missverständnisse zu vermeiden:
Die Datei befindet sich nach dem Anlegen des theme-Ordners unter `./theme/private/inc/functions.php`
