### ISSUE TITLE
Template Keys werden nicht übernommen

### ISSUE THREAD

**Issue by marcohanke** [FriendsOfREDAXO/theme#28]
Die Template Keys werden nicht mit in Theme übernommen. Im Developer sind sie in der metadata.yml, mit theme fliegen sie wieder raus.
https://github.com/FriendsOfREDAXO/developer/commit/5909dc0bae21616aa178d2ecf82b0a2f177be764

**Comment by DanielWeitenauer** [comment]
Siehe b61227e9361bda94d7c146f087dda510b7e3a36a
@marcohanke Werden damit alle Daten synchronisiert? Die neue Version ist auch im Installer verfügbar.

**Comment by marcohanke** [comment]
@DanielWeitenauer Scheint zu passen.
CIch hab aber jetzt zwei Ordner yform_email und yform_emails, vermutlich seit dem Update, kann es nicht 100%ig zuordnen.

**Comment by DanielWeitenauer** [comment]
Es gab wohl einen Tippfehler im bisherigen Erfahrungen Themen Code. yform_email ist der korrekte Developer Ordner. Dann muss der fehlerhafte Ordner beim Update noch umbenannt werden.

**Comment by DanielWeitenauer** [comment]
Der Ordner wird nun beim Update umbenannt, wenn er vorhanden ist.

**Comment by DanielWeitenauer** [comment]
@marcohanke Teste gerne nochmal.
