### ISSUE TITLE
Pfade in theme_path klasse aufnehmen

### ISSUE THREAD

**Issue by staabm** [FriendsOfREDAXO/theme#33]
Könnten diese pfade in die theme-path klasse aufgenommen werden?
- https://github.com/FriendsOfREDAXO/theme/blob/a5fa84dc5fb319bc74e91704884efc7d132b92ae/lib/developer/theme_manager.php#L66
- https://github.com/FriendsOfREDAXO/theme/blob/a5fa84dc5fb319bc74e91704884efc7d132b92ae/lib/developer/theme_manager.php#L51
- https://github.com/FriendsOfREDAXO/theme/blob/a5fa84dc5fb319bc74e91704884efc7d132b92ae/lib/developer/theme_manager.php#L84
- https://github.com/FriendsOfREDAXO/theme/blob/a5fa84dc5fb319bc74e91704884efc7d132b92ae/lib/developer/theme_manager.php#L111

ich würde die pfade für module/templates gerne in rexstan verwenden.

Falls es dort nicht reinpasst, alternativ in eine neue klasse..?

**Comment by DanielWeitenauer** [comment]
Was hast du denn genau mit den Pfaden vor? Die oben referenzierte Datei ist nur noch zur Kompatibilität mit Developer unter Version 3.6 vorhanden. Ab 3.6 hat Developer eine Methode zum Anpassen des Basispfads. Daher wäre zumindest theoretisch nicht garantiert, dass diese Pfade tatsächlich so bestehen bleiben. Je nachdem, was dein Ziel ist, wäre evtl. eine Methode direkt in Developer sinnvoller?

**Comment by staabm** [comment]
ich möchte aus dem rexstan addon heraus das theme addon befragen, unter welchem pfad module/templates abgelegt werden.

wenn das theme addon keine eigenen pfade hat, sondern die aus dem developer addon nimmt (und ich im developer addon abfragen kann welche das sind) ist das genauso gut

**Comment by DanielWeitenauer** [comment]
> unter welchem pfad module/templates abgelegt werden im filesystem.

Das ist wahrscheinlich tatsächlich besser beim Developer-Addon aufgehoben. Dort gibt es bereits `rex_developer_manager::getBasePath` für den Basispfad. Die Unterordner scheinen dann automatisiert gefunden zu werden. Ich habe allerdings auf die Schnelle nicht verstanden wie das funktioniert. Vielleicht weiß @gharlan mehr.

**Comment by DanielWeitenauer** [comment]
> Und im Synchronizer [wird dann der Pfad zusammengesetzt](https://github.com/FriendsOfREDAXO/developer/blob/master/lib/synchronizer.php#L32) aus dem BasePath und dem Unterordner.
@staabm Das sollte doch eigentlich ausreichend für dich sein, oder?
