### ISSUE TITLE
Pfad Frage

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/theme#4]
Hi,

wie muss der Pfad sein wenn ich eigen yForm Templates nutzen möchte?

ist es nicht

`theme / private / lib / yform / ytemplates / eigenes`

und dann der param:

`$yform->setObjectparams('form_ytemplate', ‘eigenes');`

Wenn ich das so mache bekomme ich Fehlermeldungen _(Warning: yform template form.tpl.php not found in...)_

Wenn ich mein "eigenes" Template direkt in den Redaxo yform ytempaltes Ordner lege funktioniert es einwandfrei...

Ich scheitere anscheinend nur an dem Pfad...

LG
Oliver

**Comment by DanielWeitenauer** [comment]
Hi Oliver,
Yform-Templates werden noch nicht automatisch eingebunden, Du musst sie manuell mit `rex_yform::addTemplatePath($pfad);` bei Yform anmelden. Einfach in der functions.php einfügen.

**Comment by DanielWeitenauer** [comment]
Ich würde sie auch nicht in den lib Ordner legen, der ist nur für Klassen gedacht, die über den Autoloader geladen werden sollen.

**Comment by olien** [comment]
Hallo Daniel,

danke. Funktioniert prima!

LG
Oliver
