### ISSUE TITLE
Inhalt von /private/ytemplate wird möglicherweise ignoriert?

### ISSUE THREAD

**Issue by dpf-dd** [FriendsOfREDAXO/theme#43]
Hallo Daniel,

ich habe ein Problem von yTemplates in Verbindung mit yForm Spam Protection... Da ich dachte, dass es eher was mit dem Spamschutz-AddOn zu tun hatte wurde das von mir initial dort beschrieben.
Bist du mal so frei und schaust da mal rein?

https://github.com/FriendsOfREDAXO/yform_spam_protection/issues/68

TLDR-kompatibel: Ich speichere mein Custom-yTemplate im Theme-Ordern `/theme/private/ytemplates`. In Verbindung mit yForm Spam Protection gibt das einen Whoop `Path cannot be null`. Lösung: yTemplate nochmal in den yForm Spam Protection Ordner kopieren - dann läuft alles...

Könnte das ein Bug im theme-AddOn sein?
Danke dir fürs Anschauen :)

Gruß,
Stefan

**Comment by DanielWeitenauer** [comment]
Hallo Stefan, das kann ich nicht nachvollziehen. Bei meinen Tests lässt sich das Template problemlos überschreiben.
Die Fehlermeldung deutet darauf hin, dass an irgend einer Stelle ein `include null` versucht wird. Das scheint mir jedoch in diesem Kontext unmöglich, da YForm den include aus Template-Pfad, Theme-Namen und Template-Namen zusammensetzt. Und mindestens der Template-Name sollte immer gesetzt sein. Nutzt du an irgendeiner Stelle includes?
Dumpe auch mal `rex_yform::$TemplatePaths` um zu prüfen, ob alle gewünschten Pfade vorhanden sind. YForm durchläuft  `rex_yform::$TemplatePaths` von hinten nach vorne, bis in einem Pfad ein passendes Template gefunden wurde.

**Comment by dpf-dd** [comment]
Mit yForm gibt es auch keine Probleme. Der Fehler tritt nur dann auf, wenn ich yForm mit dem AddOn yform_spam_protection verwende. Habe ich also ein eigenes yForm-Template im Einsatz (z.B. mit dem Namen `custom_bootstrap`) und in theme abgelegt (was wie gesagt mit yForm super flutscht) und installiere dann yform_spam_protection, dann gibt es das im o.g. Link beschriebene Problem. Meine initiale Vermutung war daher auch, dass es eher ein Problem bei yform_spam_protection ist... keine Ahnung.

Leider habe ich gerade kein Test-Redaxo am Start, um das nochmal zu reproduzieren - also mach erstmal zu hier... :)
Danke trotzdem!

**Comment by DanielWeitenauer** [comment]
OK. Allerdings kann ich auch dann kein Problem beim Überschreiben feststellen, wenn ich ein selbstbetiteltes Template verwende. Eine Möglichkeit wäre, dass eines der von YForm versteckt verwendeten Templates fehlt. YForm verwendet intern z.B. noch `value.hidden.tpl.php` für das CSRF-Token und `errors.tpl.php` für Fehlermeldungen. `errors.tpl.php` wird zum Beispiel von yform_spam_protection getriggert, wenn Warnhinweise ausgegeben werden. 
Die einfachste Lösung wäre, falls du nicht mehrere Formular-Templates aus der Website benötigst, keinen eigenen Namen für dein Template zu nutzen, sondern die Änderungen im Ordner `bootstrap` zu speichern. Eine weitere, `bootstrap` als Fallback-Template zu definieren: `objparams|form_ytemplate|custom_bootstrap,bootstrap`.
Einen technischen Fehler kann ich momentan nicht festellen und schließe hier. Falls du das Problem weiter eingrenzen kannst, kannst, gib einfach Bescheid.

**Comment by dpf-dd** [comment]
Soooo. Ich hab herausgefunden, warum das passierte.
Das Spam-Protection AddOn liefert ein Feld `value.spam_protection.tpl.php` und ergänzt damit das Standard-Bootstrap yTemplate. Und genau diese Datei war in meinem Custom-yTemplate NICHT enthalten. Dann whoopt es mit "PATH CANNOT BE EMPTY".
Hab die Datei meinem yTemplate jetzt hinzugefügt und läuft...

**Comment by DanielWeitenauer** [comment]
OK. Ich nahm an, es ginge um das Ersetzen dieser Datei. Wie oben beschrieben kannst du das Problem eines fehlenden Templates mit der Definition eines Fallback-Themes vermeiden. Dann sucht YForm alle Templates, die im Custom-Theme nicht gefunden werden auch noch einmal dort. Daher ist die Angabe des Standard-Themes `bootstrap` hier am sinnvollsten: `objparams|form_ytemplate|custom_bootstrap,bootstrap`.
