### ISSUE TITLE
Developer Addon

### ISSUE THREAD

**Issue by georgkaser** [FriendsOfREDAXO/theme#5]
Hallo!

Tolles Addon, danke dafür. 

Vielleicht kann man das mal so abändern, das der Code von Templates und Modulen ohne Developer Addon synchronisiert werden?

**Comment by DanielWeitenauer** [comment]
Hi, in der Richtung habe ich nichts geplant. Das Addon soll in erster Linie als Verwaltungshilfe dienen. Das Synchronisieren ist nicht ganz trivial und wie ich finde mit dem Developer-Addon sehr gut umgesetzt. Daher würde ich im Hinblick auf die Tatsache, dass es schon mehrere Sync-Addons gibt nicht noch eines beginnen wollen. Sollte sich der Workflow auf Dauer etablieren, würde es sich wohl eher anbieten, die Theme-Funktionen direkt im Developer-Addon anzusiedeln.

**Comment by georgkaser** [comment]
Ah, okay. Mir gings nur darum, dass ich nicht noch mehr Einträge links in der Seitenleiste hab. Versuche immer bei den Addons zu sparen, muss man auch beim Updaten nicht Angst haben, dass das eine oder andere nicht mehr läuft. Und bei deinem Addon gefällt mir eben sehr gut, dass der PHP Code direkt im Theme Ordner liegt. Übrigens auch das mit dem Sprachenordner (spart mir schon wieder ein Addon) und das mit der function.php. Super Sache, danke.

Das mit den theme_setting hab ich noch nicht ganz durchschaut, aber da arbeit ich dran :)

**Comment by olien** [comment]
Wieso spart dir der lang Ordner ein Addon? Wie nutzt Du den?

LG
Oliver

**Comment by georgkaser** [comment]
Naja, ich spar mir das Addon sprog für die Übersetzung der hartcodierten Strings. Zumindest in der Theorie - in der Praxis, bin ich draufgekommen, funktioniert das nicht. Werde mal ein Issue dazu starten, vielleicht versteh ich da was noch nicht.

**Comment by DanielWeitenauer** [comment]
Hi, der lang Ordner ist nur für Backend-Übersetzungen. Wenn du ein zweisprachiges Backend hast, kannst du so z.B. deine Modul-Texte übersetzen.

**Comment by georgkaser** [comment]
Aha, so ist das gedacht. Alles klar, dann bau ich das sprog Addon wieder ein...
