### ISSUE TITLE
Übersetzungen im lang Ordner

### ISSUE THREAD

**Issue by georgkaser** [FriendsOfREDAXO/theme#6]
Ich hab jetzt meine Übersetzungen für mein FE-Theme im lang Ordner abgelegt (de_de.lang und en_gb.lang) und die Strings entsprechend übersetzt (also pro Zeile key = String). Im Template hole ich mir die Strings jetzt via `<?php echo rex_i18n::msg('key_im_lang_file'); ?>`. In der deutschen Version funktioniert das super, der Wert wird ausgegeben. Ich hab jetzt (testweise) Englisch anglegt (bei System Code "en" und Name "english"). Wenn ich jetzt die englische Version aufrufe, dann kommt hier auch der deutsche Text.

Woran kann das liegen? Hab ich da was falsch benannt oder irgendwas noch nicht richtig verstanden?

**Comment by tbaddade** [comment]
Verwende mal im Backend die englische Sprache. Also nicht in der Struktur sondern das tatsächliche Backend.

**Comment by DanielWeitenauer** [comment]
Hi, der lang Ordner und rex_i18n sind für Backend-Übersetzungen.

**Comment by georgkaser** [comment]
Ah, okay - danke. Das ist aber schade - wär ein tolles feature gewesen...

**Comment by DanielWeitenauer** [comment]
Schon, aber da gibt es mit Sprog und Xoutputfilter schon sehr gute Lösungen, dass eine dritte Version eigentlich unnötig ist.

**Comment by tbaddade** [comment]
Man könnte das ggf. schon hinbekommen, ich sehe da nur das Problem das der Redakteur das nciht mehr selbstständig bearbeiten kann.

**Comment by georgkaser** [comment]
Das wär ja das schöne :) Manches soll der Redakteur gar nicht ändern können.

**Comment by DanielWeitenauer** [comment]
Das wäre dann eher ein Featurewunsch für die oben genannten Addons ;)

**Comment by georgkaser** [comment]
Nein, eigentlich nicht. Ich kann dem Redakteur die nötigen Rechte dafür vorenthalten.

Ich suche halt eher ein Theme Addon wo ich alles für mein Frontend Theme verwalten kann. Ähnlich wie bei Wordpress. Wo ich alle nötigen Dateien mitliefern kann (unabhängig von der REDAXO Version, Datenbanken automatisch installieren und welches auch die nötigen Addons automatisch installiert. Komplett Dummy-User geeignet - man kopiert das Theme in den REDAXO Root Ordner, klickt auf installieren und die Seite läuft. Hach, das wär schön ;)

Backend interessiert mich da eigentlich nicht wirklich - ich finde das Backend gut so wie es ist.

**Comment by DanielWeitenauer** [comment]
Ansonsten kannst du im inc Ordner einfach eine Date anlegen, in der Du ein Array mit den lang-keys und deinen Texten definierst, die hast du dann überall zur Verfügung:

```
// z.B. in der functions.php
$translations = array(
     0 => array( 'key' => 'Text deutsch', ... ),
     1 => array( 'key' => 'Text englisch', ... ),
);

// Ausgabe
echo $translations[rex_clang::getCurrentId()]['key'];
```

**Comment by georgkaser** [comment]
Daran hab ich auch grad gedacht - dank dir!

**Comment by DanielWeitenauer** [comment]
Wer weiß, wenn der Installer Abhängigkeiten automatisch installieren kann, ist es vielleicht nur noch ein kleiner Schritt zu echten, einfach installierbaren Themes.

**Comment by georgkaser** [comment]
das wär der Knaller 👍
