### ISSUE TITLE
Weitere Ordner automatisch einbinden

### ISSUE THREAD

**Issue by DanielWeitenauer** [FriendsOfREDAXO/theme#7]
- [x] Fragments 
- [x] YForm Templates?

**Comment by olien** [comment]
Beide bitte!!!

**Comment by harrybrader** [comment]
Ja gerne beide

**Comment by alexwenz** [comment]
+1

**Comment by olien** [comment]
Ich arbeite gerade zum erstenmal mit Fragmenten... Ist cool. Würde mich über den ORdner sehr freuen :-))))

LG
Oliver

**Comment by dtpop** [comment]
Das mit den Fragmenten wäre ein echtes Highlight. Das ist grade ein echter Hype seit Fulda.

**Comment by alexwenz** [comment]
+1 (für Ordner)
+1 (für auskommentierte addTemplatePath-Zeile)

**Comment by IngoWinter** [comment]
https://github.com/FriendsOfREDAXO/theme/pull/11

**Comment by DanielWeitenauer** [comment]
Ist non endlich eingefügt.
